
data("cars")
head(cars)
scatter.smooth(x = cars$speed, y = cars$dist, main="Dist~Speed")  
par(mfrow= c(1, 2))
boxplot(cars$speed, main="Speed", sub = paste("outlier rows:", boxplot.stats(cars$speed)$out ))
boxplot(cars$dist, main = "Distance", sub= paste("outlier rows:", boxplot.stats(cars$dist)$out))
library(e1071)
par(mfrow= c(1, 2))
plot(density(cars$speed), main= "Density_Plot_Speed", y="Frequency", sub = paste("skewness:", round(e1071::skewness(cars$speed), 2) ))
polygon(density(cars$speed), col = 'red')
plot(density(cars$dist), main = "Density_plot_Distance", y = "frequency", sub = paste("sKewness", round(e1071::skewness(cars$dist), 2)))
polygon(density(cars$dist), col = 'blue')
linearMod<- lm(dist~speed, data = cars)
print(linearMod)
summary(linearMod)
